update openshift operator with keycloak changes
xebialabs/xl-release-kubernetes-operator pull request #19
Opened 2021-12-29 08:05 UTC by ommkar-xl

For the updated image, use
docker pull xldevdocker/release-operator:1.3.0-openshift

2021-12-29 13:19 UTC, rprasad-digitalai commented on release-operator-openshift/digitalai-release/kubernetes/dairelease_cr.yaml
> -  # Secrets must be manually created in the namespace
Please restore the image pull secret changes.

2021-12-29 13:24 UTC, rprasad-digitalai requested changes
Restore the image pull secret

2021-12-30 04:23 UTC, ommkar-xl commented on release-operator-openshift/digitalai-release/kubernetes/dairelease_cr.yaml
> -  # Secrets must be manually created in the namespace
Not required. The Openshift helm chart values.yaml doesn't have PullSecrets for XL-Release.

2021-12-30 04:24 UTC, ommkar-xl commented on release-operator-openshift/digitalai-release/kubernetes/dairelease_cr.yaml
> -  # Secrets must be manually created in the namespace
In the case of Openshift, the image pull secret can be used with a service account.

2021-12-30 04:37 UTC, rprasad-digitalai approved these changes
Looks good to me

2021-12-30 04:40 UTC, merged